name:                serendipity
version:             0.1.0.0
github:              "nilp0inter/serendipity"
license:             BSD3
author:              "Roberto Abdelkader Martínez Pérez"
maintainer:          "robertomartinezp@gmail.com"
copyright:           "2021 Roberto Abdelkader Martínez Pérez"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nilp0inter/serendipity#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- wai
- warp
- servant-static-th

library:
  source-dirs: src

executables:
  serendipity-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - serendipity

tests:
  serendipity-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - serendipity
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
