name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Cache nix store
      uses: actions/cache@v2
      with:
        path: /nix/store
        key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}-${{ hashFiles('default.nix') }}
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: nilp0inter-serendipity-build
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Cache Haskell dependencies (Stack)
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('serendipity.cabal') }}
    - run: nix-shell --run "make test"
