name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: nilp0inter-serendipity-build
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Cache Haskell dependencies (Stack)
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('serendipity.cabal') }}
        path: |
          ~/.stack
          .stack-work
    - name: Cache Purescript dependencies (Spago)
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-spago-${{ hashFiles('webapp/*.dhall') }}
        path: |
          webapp/.spago
          webapp/output
    - run: nix-shell --run "make test"
